{
  "comments": [
    {
      "key": {
        "uuid": "5a3f45e8_9d72ade1",
        "filename": "api/resources/v1/env.py",
        "patchSetId": 1
      },
      "lineNbr": 275,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-03-20T16:53:45Z",
      "side": 1,
      "message": "\"installer_ip\" must be unicode in PY27. In PY3 it doesn\u0027t matter, all text is unicode.\n\nYou can use six:\nstr(ipaddress.IPv4Address(six.u(installer_ip)))\n\n\n\u003e\u003e\u003e ipaddress.IPv4Address(\u00271.2.3.4\u0027)\nTraceback (most recent call last):\n  File \"\u003cstdin\u003e\", line 1, in \u003cmodule\u003e\n  File \"/usr/local/lib/python2.7/dist-packages/ipaddress.py\", line 1391, in __init__\n    self._check_packed_address(address, 4)\n  File \"/usr/local/lib/python2.7/dist-packages/ipaddress.py\", line 554, in _check_packed_address\n    expected_len, self._version))\nipaddress.AddressValueError: \u00271.2.3.4\u0027 (len 7 !\u003d 4) is not permitted as an IPv4 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?\n\n\n\u003e\u003e\u003e ipaddress.IPv4Address(u\u00271.2.3.4\u0027)\nIPv4Address(u\u00271.2.3.4\u0027)",
      "range": {
        "startLine": 275,
        "startChar": 61,
        "endLine": 275,
        "endChar": 73
      },
      "revId": "8243b8aa6f96bb07044fec77e846488b079c2706",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}