{
  "comments": [
    {
      "key": {
        "uuid": "9a561d44_66404057",
        "filename": "yardstick/common/kubernetes_utils.py",
        "patchSetId": 4
      },
      "lineNbr": 253,
      "author": {
        "id": 2311
      },
      "writtenOn": "2018-07-19T09:57:17Z",
      "side": 1,
      "message": "An API exception should be handled appropriately.\n\nOtherwise, we assume that the network does not exist, which is not what this exception implies.\n\nVolodymyr\u0027s change might be relevant:\nhttps://gerrit.opnfv.org/gerrit/#/c/59949",
      "range": {
        "startLine": 253,
        "startChar": 8,
        "endLine": 253,
        "endChar": 14
      },
      "revId": "a7e6671c7f5fa717480475ad56c481f31fee0649",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a561d44_51ffb401",
        "filename": "yardstick/common/kubernetes_utils.py",
        "patchSetId": 4
      },
      "lineNbr": 253,
      "author": {
        "id": 7075
      },
      "writtenOn": "2018-07-19T10:55:30Z",
      "side": 1,
      "message": "except ApiException as e:\n        if e.status in [404]:\n            network \u003d None\n        else:\n            raise exceptions.KubernetesApiException(\n                action\u003d\u0027get\u0027, resource\u003d\u0027Custom Object: Network\u0027)",
      "parentUuid": "9a561d44_66404057",
      "range": {
        "startLine": 253,
        "startChar": 8,
        "endLine": 253,
        "endChar": 14
      },
      "revId": "a7e6671c7f5fa717480475ad56c481f31fee0649",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}