{
  "comments": [
    {
      "key": {
        "uuid": "5aaae553_f4ab66d4",
        "filename": "yardstick/benchmark/scenarios/availability/monitor/monitor_multi.py",
        "patchSetId": 3
      },
      "lineNbr": 66,
      "author": {
        "id": 1247
      },
      "writtenOn": "2017-05-24T06:42:24Z",
      "side": 1,
      "message": "in the subclasss.verify_SLA(), they only get the \"outage_time\" and check with that items. It seems that you didn\u0027t update the outage_time, but only update the first and last time.",
      "range": {
        "startLine": 66,
        "startChar": 31,
        "endLine": 66,
        "endChar": 44
      },
      "revId": "dba19dbc77d23d68e899cd7a18c41f1f8f726106",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}